version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5000:5000"

  database:
    container_name: db
    image: mysql:5.7.12
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: example
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: dev