version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db

  database:
    container_name: db
    image: mysql:5.7.12
    healthcheck:
      test: "/usr/bin/mysql --database=example --user=exampleuser --password=dev -e 'select 1;' --silent"
      start_period: 10s
      interval: 5s
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: example
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: dev
